/**
 * Gallery manifest — the photographs shown on /gallery.
 * Sourced from https://joseacestudios56.pixieset.com/greenngoria/.
 * Filtered to remove redundant burst shots and identical viewpoints.
 */

export interface GalleryImage {
  src: string;
  width: number;
  height: number;
  alt: string;
  category?: string;
}

export const galleryImages: GalleryImage[] = [
  {
    src: '/images/gallery/greenngoria-01.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 1',
  },
  {
    src: '/images/gallery/greenngoria-04.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 2',
  },
  {
    src: '/images/gallery/greenngoria-06.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 3',
  },
  {
    src: '/images/gallery/greenngoria-08.webp',
    width: 1024,
    height: 775,
    alt: 'Green Ngoria Supplies — Photograph 4',
  },
  {
    src: '/images/gallery/greenngoria-09.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 5',
  },
  {
    src: '/images/gallery/greenngoria-10.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 6',
  },
  {
    src: '/images/gallery/greenngoria-12.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 7',
  },
  {
    src: '/images/gallery/greenngoria-14.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 8',
  },
  {
    src: '/images/gallery/greenngoria-15.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 9',
  },
  {
    src: '/images/gallery/greenngoria-17.webp',
    width: 1024,
    height: 683,
    alt: 'Green Ngoria Supplies — Photograph 10',
  },
  {
    src: '/images/gallery/dji-0308.webp',
    width: 3600,
    height: 2025,
    alt: 'Green Ngoria Supplies — Photograph 11',
  },
  {
    src: '/images/gallery/dji-0314.webp',
    width: 3600,
    height: 2025,
    alt: 'Green Ngoria Supplies — Photograph 12',
  },
  {
    src: '/images/gallery/dji-0318.webp',
    width: 3600,
    height: 1870,
    alt: 'Green Ngoria Supplies — Photograph 13',
  },
  {
    src: '/images/gallery/dji-0323.webp',
    width: 3600,
    height: 2025,
    alt: 'Green Ngoria Supplies — Photograph 14',
  },
  {
    src: '/images/gallery/dji-0328.webp',
    width: 3600,
    height: 2025,
    alt: 'Green Ngoria Supplies — Photograph 15',
  },
  {
    src: '/images/gallery/dji-0333.webp',
    width: 3600,
    height: 2025,
    alt: 'Green Ngoria Supplies — Photograph 16',
  },
  {
    src: '/images/gallery/ace4036.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 17',
  },
  {
    src: '/images/gallery/ace4037.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 18',
  },
  {
    src: '/images/gallery/ace4039.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 19',
  },
  {
    src: '/images/gallery/ace4041.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 20',
  },
  {
    src: '/images/gallery/ace4042.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 21',
  },
  {
    src: '/images/gallery/ace4043.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 22',
  },
  {
    src: '/images/gallery/ace4044.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 23',
  },
  {
    src: '/images/gallery/ace4045.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 24',
  },
  {
    src: '/images/gallery/ace4049.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 25',
  },
  {
    src: '/images/gallery/ace4050.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 26',
  },
  {
    src: '/images/gallery/ace4052.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 27',
  },
  {
    src: '/images/gallery/ace4054.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 28',
  },
  {
    src: '/images/gallery/ace4055.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 29',
  },
  {
    src: '/images/gallery/ace4057.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 30',
  },
  {
    src: '/images/gallery/ace4060.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 31',
  },
  {
    src: '/images/gallery/ace4063.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 32',
  },
  {
    src: '/images/gallery/ace4065.webp',
    width: 2880,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 33',
  },
  {
    src: '/images/gallery/ace4067.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 34',
  },
  {
    src: '/images/gallery/ace4068.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 35',
  },
  {
    src: '/images/gallery/ace4069.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 36',
  },
  {
    src: '/images/gallery/ace4071.webp',
    width: 2880,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 37',
  },
  {
    src: '/images/gallery/ace4073.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 38',
  },
  {
    src: '/images/gallery/ace4075.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 39',
  },
  {
    src: '/images/gallery/ace4079.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 40',
  },
  {
    src: '/images/gallery/ace4082.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 41',
  },
  {
    src: '/images/gallery/ace4085.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 42',
  },
  {
    src: '/images/gallery/ace4086.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 43',
  },
  {
    src: '/images/gallery/ace4087.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 44',
  },
  {
    src: '/images/gallery/ace4088.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 45',
  },
  {
    src: '/images/gallery/ace4090.webp',
    width: 3600,
    height: 2558,
    alt: 'Green Ngoria Supplies — Photograph 46',
  },
  {
    src: '/images/gallery/ace4094.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 47',
  },
  {
    src: '/images/gallery/ace4096.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 48',
  },
  {
    src: '/images/gallery/ace4097.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 49',
  },
  {
    src: '/images/gallery/ace4101.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 50',
  },
  {
    src: '/images/gallery/ace4102.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 51',
  },
  {
    src: '/images/gallery/ace4105.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 52',
  },
  {
    src: '/images/gallery/ace4106.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 53',
  },
  {
    src: '/images/gallery/ace4109.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 54',
  },
  {
    src: '/images/gallery/ace4111.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 55',
  },
  {
    src: '/images/gallery/ace4112.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 56',
  },
  {
    src: '/images/gallery/ace4113.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 57',
  },
  {
    src: '/images/gallery/ace4114.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 58',
  },
  {
    src: '/images/gallery/ace4115.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 59',
  },
  {
    src: '/images/gallery/ace4116.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 60',
  },
  {
    src: '/images/gallery/ace4117.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 61',
  },
  {
    src: '/images/gallery/ace4118.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 62',
  },
  {
    src: '/images/gallery/ace4121.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 63',
  },
  {
    src: '/images/gallery/ace4126.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 64',
  },
  {
    src: '/images/gallery/ace4128.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 65',
  },
  {
    src: '/images/gallery/ace4130.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 66',
  },
  {
    src: '/images/gallery/ace4131.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 67',
  },
  {
    src: '/images/gallery/ace4132.webp',
    width: 2880,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 68',
  },
  {
    src: '/images/gallery/ace4133.webp',
    width: 2400,
    height: 3600,
    alt: 'Green Ngoria Supplies — Photograph 69',
  },
  {
    src: '/images/gallery/ace4137.webp',
    width: 3600,
    height: 2400,
    alt: 'Green Ngoria Supplies — Photograph 70',
  },
];
